### ISSUE TITLE
Add new states and fully qualified collection name in examples for the older Resource Modules

### ISSUE THREAD

**Issue by trishnaguha** [ansible-collections/cisco.iosxr#16]
##### SUMMARY

Add gathered, rendered, parsed support to the following RMs:
  - [x] iosxr_interfaces (@rohitthakur2590 ) : https://github.com/ansible-collections/cisco.iosxr/pull/18
  - [x] iosxr_l2_interfaces (@rohitthakur2590 ): https://github.com/ansible-collections/cisco.iosxr/pull/19
  - [x] iosxr_l3_interfaces (@rohitthakur2590 ): https://github.com/ansible-collections/cisco.iosxr/pull/20
  - [x] iosxr_lacp (@rohitthakur2590 ): https://github.com/ansible-collections/cisco.iosxr/pull/21
  - [x] iosxr_lacp_interfaces (@GomathiselviS) #23 
  - [x] iosxr_lag_interfaces (@GomathiselviS) #22 
  - [x] iosxr_lldp_global (@GomathiselviS) #24 
  - [x] iosxr_lldp_interfaces (@GomathiselviS) #24 

##### ISSUE TYPE
- Feature Idea

**Comment by trishnaguha** [comment]
cc @GomathiselviS @rohitthakur2590
